# Google Cloud App Engine configuration for React frontend

runtime: nodejs18

# Environment variables
env_variables:
  REACT_APP_API_URL: "https://your-backend-url.appspot.com/api/v1"

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65

# Handlers
handlers:
  # Static files
  - url: /static
    static_dir: build/static
    
  # Catch-all handler for React Router
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
