# Google Cloud App Engine configuration for chatbot-with-memory

runtime: python39

# Environment variables
env_variables:
  OPENAI_API_KEY: "your_openai_api_key_here"
  DATABASE_URL: "sqlite:///./chat.db"
  HOST: "0.0.0.0"
  PORT: "8080"
  DEBUG: "False"
  ALLOWED_ORIGINS: "https://your-frontend-url.appspot.com"

# Automatic scaling
automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65

# Health check
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

# Handlers
handlers:
  # Static files (if any)
  - url: /static
    static_dir: static
    
  # API routes
  - url: /api/.*
    script: auto
    
  # Health check
  - url: /health
    script: auto
    
  # Catch-all handler
  - url: /.*
    script: auto
